version: '2'

services:
   db:
     env_file: mysql.env
     image: mysql:8
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress

   wordpress:
     env_file: wordpress.env
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - html:/var/www/html
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_NAME: wordpress
volumes:
    db_data: {}
    html: {}
